### PR TITLE
isErrorFromAlias retruns false incorrectly

### PR DESCRIPTION
**Pull request by maantje**
Hey,

It seems like isErrorFromAlias and isErrorFromPath don't work when a parameter is used.

I think the issue is in [this line](https://github.com/ecyrbe/zodios/blob/ac62b3b1de12ebba3dbb50c1bc06175945f7674b/src/utils.ts#L119) since `endpoint.path` contains the placeholder e.g :id while `err.config.url` contains the actual value.

### CODE REVIEW

**Comment by ecyrbe** [comment]
Hello, i thank you are completely right. Would you be up for the job to also provide a fix ?

**Comment by maantje** [comment]
Hey @ecyrbe ,

Thanks for replying, I gave it a shot to provide a fix. 

Let me know if you require any changes.

**Comment by ecyrbe** [comment]
Thanks you a lot. I see now that my suggestion was not workable, since it required you to change the api and to pass the path params.
I'm really sorry to have misslead you into this solution.
So i think a better way will be to use a regexp to match the endpoint. This way no need to add path params.
If you see what i mean, could you try that instead?
Else i'll provide it

**Comment by maantje** [comment]
No worries, I refactored the code to use regexp. 

Is this what you had it in mind?

**Comment by ecyrbe** [comment]
@maantje exactly. you nailed it. thank you.

**Comment by ecyrbe** [comment]
just created a `v10.7.6` of `@zodios/core` containing this fix.

**Comment by maantje** [comment]
That is great to hear, thank you for reviewing and merging!

**Pull request merged**
